/*
 * Julianne Wojdak
 * 11/01/19
 * Rock, Paper, Scissors Culminating Project Screen 1
 */

/**
 *
 * @author JuWoj8013
 */
public class FormCulminating extends javax.swing.JFrame {
    //Lives always start at 5
    int lives = 5;
    /**
     * Creates new form FormCulminating
     */
    public FormCulminating() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        CompNumLabel = new javax.swing.JLabel();
        CompNumLabel2 = new javax.swing.JLabel();
        LivesLabel = new javax.swing.JLabel();
        LivesNumLabel = new javax.swing.JLabel();
        ResultsLabel = new javax.swing.JLabel();
        RockBtn = new javax.swing.JButton();
        PaperBtn = new javax.swing.JButton();
        ScissorsBtn = new javax.swing.JButton();
        ClickLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        HeadingLabel.setFont(new java.awt.Font("Swis721 Ex BT", 0, 18)); // NOI18N
        HeadingLabel.setText("Rock Paper Scissors!");

        CompNumLabel.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        CompNumLabel.setText("Computer Choice:");

        CompNumLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N

        LivesLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 11)); // NOI18N
        LivesLabel.setText("Lives:");

        LivesNumLabel.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        LivesNumLabel.setText("5");

        ResultsLabel.setFont(new java.awt.Font("Swis721 Ex BT", 0, 24)); // NOI18N

        RockBtn.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        RockBtn.setText("Rock");
        RockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RockBtnActionPerformed(evt);
            }
        });

        PaperBtn.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        PaperBtn.setText("Paper");
        PaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperBtnActionPerformed(evt);
            }
        });

        ScissorsBtn.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        ScissorsBtn.setText("Scissors");
        ScissorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScissorsBtnActionPerformed(evt);
            }
        });

        ClickLabel.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        ClickLabel.setText("Click One!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RockBtn)
                    .addComponent(ClickLabel)
                    .addComponent(PaperBtn)
                    .addComponent(ScissorsBtn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(HeadingLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CompNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CompNumLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(LivesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LivesNumLabel)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HeadingLabel)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LivesLabel)
                                    .addComponent(LivesNumLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CompNumLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ClickLabel)
                        .addComponent(CompNumLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RockBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PaperBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScissorsBtn))
                    .addComponent(ResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action For "Rock" Button
     *
     * @param evt 
     */
    private void RockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RockBtnActionPerformed
        //Constants
        int userNum;
        int compNum;
        userNum = 1;
        
        //Changing Variable
        compNum = (int)Math.round(Math.random()*3+1);
        
        //Processing
        if (compNum == 1)
        {
            CompNumLabel2.setText("Rock");
        }
        if (compNum == 2)
        {
          CompNumLabel2.setText("Paper");          
        }
        if (compNum == 3)
        {
          CompNumLabel2.setText("Scissors");
        }
        if (userNum == 1)
        {
            if (compNum == 1)
            {
              ResultsLabel.setText("It's a tie!");
            }
            if (compNum == 2)
            {
              ResultsLabel.setText("You lose!");
              lives = lives - 1;
            }
            if (compNum == 3)
            {
              ResultsLabel.setText("You win!");
            }
        }
        
        //Display
        LivesNumLabel.setText(""+ lives);
       
        //Set To Game Over Screen
        if (lives == 0)
        {
        this.setVisible(false);
        new FormCulminating2().setVisible(true);
        }
    }//GEN-LAST:event_RockBtnActionPerformed

    /**
     * Action For "Paper" Button
     * @param evt 
     */
    private void PaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaperBtnActionPerformed
        //Constants
        int userNum;
        int compNum;
        userNum = 2;
        
        //Changing Variable
        compNum = (int)Math.round(Math.random()*3+1);
        
        //Processing
        if (compNum == 1)
        {
            CompNumLabel2.setText("Rock");
        }
        if (compNum == 2)
        {
          CompNumLabel2.setText("Paper");          
        }
        if (compNum == 3)
        {
          CompNumLabel2.setText("Scissors");
        }
        if (userNum == 2)
        {
            if (compNum == 1)
            {
              ResultsLabel.setText("You win!");
            }
            if (compNum == 2)
            {
              ResultsLabel.setText("It's a tie!");
            }
            if (compNum == 3)
            {
              ResultsLabel.setText("You lose!");
              lives = lives - 1;
            }
        }
        //Display
        LivesNumLabel.setText(""+ lives);
        
        //Set To Game Over Screen
        if (lives == 0)
        {
        this.setVisible(false);
        new FormCulminating2().setVisible(true);
        }
    }//GEN-LAST:event_PaperBtnActionPerformed

    /**
     * Action For "Scissors" Button
     * @param evt 
     */
    private void ScissorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScissorsBtnActionPerformed
        //Constants
        int userNum;
        int compNum;
        userNum = 3;
        
        //Changing Variable
        compNum = (int)Math.round(Math.random()*3+1);
        
        //Processing
        if (compNum == 1)
        {
            CompNumLabel2.setText("Rock");
        }
        if (compNum == 2)
        {
          CompNumLabel2.setText("Paper");          
        }
        if (compNum == 3)
        {
          CompNumLabel2.setText("Scissors");
        }
        if (userNum == 3)
        {
            if (compNum == 1)
            {
              ResultsLabel.setText("You lose!");
              lives = lives - 1;
            }
            if (compNum == 2)
            {
              ResultsLabel.setText("You win!");
            }
            if (compNum == 3)
            {
              ResultsLabel.setText("It's a tie!");
            }
        }
        
        //Display
        LivesNumLabel.setText(""+ lives);
        
        //Set To Game Over Screen
        if (lives == 0)
        {
        this.setVisible(false);
        new FormCulminating2().setVisible(true);
        }
    }//GEN-LAST:event_ScissorsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCulminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCulminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCulminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCulminating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCulminating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickLabel;
    private javax.swing.JLabel CompNumLabel;
    private javax.swing.JLabel CompNumLabel2;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JLabel LivesLabel;
    private javax.swing.JLabel LivesNumLabel;
    private javax.swing.JButton PaperBtn;
    private javax.swing.JLabel ResultsLabel;
    private javax.swing.JButton RockBtn;
    private javax.swing.JButton ScissorsBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
